version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    container_name: server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hackathon_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata: